### ISSUE TITLE
The case only one element in candidate list will still return None

### ISSUE THREAD

**Issue by Derekkk** [magic282/cnndm_acl18#1]
Hi,

Thanks for sharing the code. I noticed there might be a bug in line 42 of find_oracle.py:

```
all_best_l = 1
    all_best_score = 0
    all_best_comb = None
    for l in range(1, len(candidates)):
        if l > MAX_COMB_L:
```

Here you always assume there should be at least 2 elements in the candidate list, right? If there's only 1 candidate, you never dive into the loop and just return (None, 0).

I'm not sure if you did this for some reason or just a bug?

**Comment by magic282** [comment]
Hi @Derekkk , thank you for your reminder. I am aware of this bug recently when processing another dataset. So I changed line 43 to
```python
for l in range(1, len(candidates) + 1):
```
