### ISSUE TITLE
Output to described model

### ISSUE THREAD

**Issue by princeamitlali** [magic282/cnndm_acl18#3]
Someone please suggest how to follow step 2. Change the output to train.txt.src and train.txt.tgt.

**Comment by NileshPranami** [comment]
I am also bit confused about that.
Thanks @princeamitlali to create this issue.
Please someone answer this.

**Comment by magic282** [comment]
Please change the data format according to the sample data. The data with the sample format is all you need.

**Comment by princeamitlali** [comment]
But how to change we get tokanized and .bin files but we are required .txt file, please suggest us

**Comment by magic282** [comment]
You need to write some code to convert the bin format to txt.

**Comment by princeamitlali** [comment]
We convert the bin file to corresponding .txt file but how to generate .src and .txt file from that corresponding .txt file please help

**Comment by magic282** [comment]
.src file contains the document. .tgt file contains the summary. Please follow the format in the sample data.

**Comment by gnepul-ace** [comment]
Can you provide codes to create files formatted as step2?
